version: '3.8'

services:
  oracle-db:
    container_name: oracle-db
    image: container-registry.oracle.com/database/free:latest
    restart: unless-stopped
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PWD: StrongPassword123
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - /home/shaxriyor/oracle-data:/opt/oracle/oradata
    networks:
      - library-network
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/StrongPassword123@localhost:1521/FREEPDB1 > /dev/null 2>&1 || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 20
      start_period: 300s
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 2G

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "0.0.0.0", "--requirepass", "redispass123"]
    volumes:
      - redis_data:/data
    networks:
      - library-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redispass123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    networks:
      - library-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  registr-service:
    build: ./registr
    container_name: service-registr
    ports:
      - "8761:8761"
    networks:
      - library-network
    depends_on:
      rabbitmq:
        condition: service_healthy
      oracle-db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=StrongPassword123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s

  auth-service:
    build: ./auth
    container_name: auth-service
    ports:
      - "8082:8082"
    networks:
      - library-network
    depends_on:
      registr-service:
        condition: service_healthy
      oracle-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=StrongPassword123
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registr-service:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=redispass123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 90s

  order-service:
    build: ./order
    container_name: order-service
    ports:
      - "8081:8081"
    networks:
      - library-network
    depends_on:
      registr-service:
        condition: service_healthy
      oracle-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=StrongPassword123
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registr-service:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 90s

  payment-service:
    build:
      context: ./payment
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "9002:9002"
    networks:
      - library-network
    depends_on:
      registr-service:
        condition: service_healthy
      oracle-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=StrongPassword123
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registr-service:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password
      - SPRING_RABBITMQ_VIRTUAL_HOST=/
      - SERVER_PORT=9002
      - SERVER_SERVLET_CONTEXT_PATH=/payment-service
      - PAYME_MERCHANT_ID=65dca8e90412e2000198a7a8
      - PAYME_MERCHANT_KEY=key_for_test_environment_12345
      - PAYME_CHECKOUT_URL=https://test.paycom.uz
      - PAYME_ALLOWED_IPS=91.232.226.0/24,185.184.12.0/24,127.0.0.1,172.17.0.0/16,172.18.0.0/16
      - CLICK_MERCHANT_SERVICE_ID=84443
      - CLICK_MERCHANT_SECRET_KEY=brgrW88TGYBpsAdocks
      - CLICK_MERCHANT_ID=test_click_merchant_id
      - CLICK_CHECKOUT_URL=https://my.click.uz/services/pay
      - CLICK_ALLOWED_IPS=91.232.226.0/24,185.184.12.0/24,127.0.0.1,172.17.0.0/16,172.18.0.0/16
      - PAYMENT_IDEMPOTENCY_EXPIRY_HOURS=24
      - PAYMENT_TRANSACTION_TIMEOUT_MINUTES=30
      - PAYMENT_MAX_RETRY_ATTEMPTS=3
      - LOGGING_LEVEL_COM_EXAMPLE_PAYMENTSERVICE=DEBUG
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=DEBUG
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:+UseG1GC -Djava.security.egd=file:/dev/./urandom
    volumes:
      - payment-logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/payment-service/actuator/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s
    restart: unless-stopped

  gateway-service:
    build: ./gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    networks:
      - library-network
    depends_on:
      registr-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      order-service:
        condition: service_healthy
      payment-service:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registr-service:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 90s

networks:
  library-network:
    driver: bridge

volumes:
  rabbitmq_data:
  rabbitmq_logs:
  redis_data:
  payment-logs: