version: '3.8'

services:
  # База данных Oracle
  oracle-db:
    container_name: oracle-db
    image: container-registry.oracle.com/database/free:latest
    restart: unless-stopped
    ports:
      - "1521:1521"
      - "5501:5500"
    environment:
      ORACLE_PWD: StrongPassword123
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - library-network
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'SELECT 1 FROM DUAL;' | sqlplus -L system/StrongPassword123@//localhost:1521/FREEPDB1"]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 120s

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - library-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Message Broker RabbitMQ
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    networks:
      - library-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Service Discovery - Eureka Server
  registr-service:
    build: ./registr
    container_name: service-registr
    ports:
      - "8761:8761"
    networks:
      - library-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Authentication Service
  auth-service:
    build: ./auth
    container_name: auth-service
    ports:
      - "8082:8082"
    networks:
      - library-network
    depends_on:
      registr-service:
        condition: service_healthy
      oracle-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=StrongPassword123
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registr-service:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s

  # Order Service
  order-service:
    build: ./order
    container_name: order-service
    ports:
      - "8081:8081"
    networks:
      - library-network
    depends_on:
      registr-service:
        condition: service_healthy
      oracle-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=StrongPassword123
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registr-service:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s

  # Payment Service (ОБНОВЛЕННЫЙ)
  payment-service:
    build:
      context: ./payment
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "9002:9002"
    networks:
      - library-network
    depends_on:
      registr-service:
        condition: service_healthy
      oracle-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker

      # Database
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/FREEPDB1
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=StrongPassword123

      # Service Discovery
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registr-service:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true

      # RabbitMQ
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=user
      - SPRING_RABBITMQ_PASSWORD=password
      - SPRING_RABBITMQ_VIRTUAL_HOST=/

      # Server
      - SERVER_PORT=9002
      - SERVER_SERVLET_CONTEXT_PATH=/payment-service

      # Payme Configuration
      - PAYME_MERCHANT_ID=65dca8e90412e2000198a7a8
      - PAYME_MERCHANT_KEY=key_for_test_environment_12345
      - PAYME_CHECKOUT_URL=https://test.paycom.uz
      - PAYME_ALLOWED_IPS=91.232.226.0/24,185.184.12.0/24,127.0.0.1,172.0.0.0/8

      # Click Configuration
      - CLICK_MERCHANT_SERVICE_ID=84443
      - CLICK_MERCHANT_SECRET_KEY=brgrW88TGYBpsA
      - CLICK_MERCHANT_ID=test_click_merchant_id
      - CLICK_CHECKOUT_URL=https://my.click.uz/services/pay
      - CLICK_ALLOWED_IPS=91.232.226.0/24,185.184.12.0/24,127.0.0.1,172.0.0.0/8

      # Payment Settings
      - PAYMENT_IDEMPOTENCY_EXPIRY_HOURS=24
      - PAYMENT_TRANSACTION_TIMEOUT_MINUTES=30
      - PAYMENT_MAX_RETRY_ATTEMPTS=3

      # Logging
      - LOGGING_LEVEL_COM_EXAMPLE_PAYMENTSERVICE=DEBUG
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=DEBUG

      # JVM Options
      - JAVA_OPTS=-Xms512m -Xmx1024m -XX:+UseG1GC -Djava.security.egd=file:/dev/./urandom

    volumes:
      - payment-logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9002/payment-service/actuator/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 90s
    restart: unless-stopped

  # API Gateway
  gateway-service:
    build: ./gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    networks:
      - library-network
    depends_on:
      registr-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      order-service:
        condition: service_healthy
      payment-service:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registr-service:8761/eureka/
      - EUREKA_INSTANCE_PREFERIPADDRESS=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s

networks:
  library-network:
    driver: bridge

volumes:
  oracle-data:
  rabbitmq_data:
  rabbitmq_logs:
  redis_data:
  payment-logs: