services:
  registr-service:
    build: ./registr
    container_name: registr-service
    ports:
      - "8761:8761"
    networks:
      - library-network

  gateway-service:
    build: ./gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - registr-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - library-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  auth-service:
    build: ./auth
    container_name: auth-service
    ports:
      - "8082:8082"
    depends_on:
      - registr-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - library-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  order-service:
    build: ./order
    container_name: order-service
    ports:
      - "8081:8081"
    depends_on:
      - registr-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - library-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  payment-service:
    build: ./payment
    container_name: payment-service
    ports:
      - "9002:9002"
    depends_on:
      - registr-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - library-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  library-network:
    driver: bridge

