package auth_service.auth.entity;

public enum AuditEventType {
    USER_REGISTERED,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILURE,
    USER_LOGOUT,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_SUCCESS,
    EMAIL_VERIFIED,

    ADMIN_USER_STATUS_CHANGED,
    ADMIN_USER_ROLE_CHANGED
}
